### ISSUE TITLE
درخواست راهنمایی برای پیاده‌سازی قلم

### ISSUE THREAD

**Issue by ekm507** [MDarvishi5124/Unixel#6]
سلام
برای ساخت قلم پیکسلی از چه نرم‌افزاری استفاده می‌کنید؟
من تمایل دارم قلم پیکسلی [چهار](https://github.com/ekm507/chahar-font) را که برای سیستم‌های الکترونیکی طراحی کرده بودم، برای استفاده در رایانه دوباره پیاده‌سازی کنم.
قدردان هر راهنمایی دیگری نیز خواهم بود.
با سپاس

**Comment by MDarvishi5124** [comment]
قلم چهار رو دوست دارم، نوع طراحیش جالبه برام
من قلم ها رو با نرم افزار های آزاد طراحی نمیکنم، با Fontcreator or Fontlab
اما علاوه بر فونت‌فورج نرم افزار Microsoft Volt هم هست که برای شما کار سازه، داخلش میتونید اسکریپت فونت رو طراحی کنید(البته طراحیش قدیمیه و کار باهاش سخته)
[این پیوست از سایت فونتامین](https://fontamin.com/%d8%b3%d8%a7%d8%b2%d9%86%d8%af%da%af%d8%a7%d9%86-%d9%81%d9%88%d9%86%d8%aa-%d9%81%d8%a7%d8%b1%d8%b3%db%8c-%d8%a7%d8%b2-%da%86%d9%87-%d9%86%d8%b1%d9%85%e2%80%8c%d8%a7%d9%81%d8%b2%d8%a7%d8%b1%d9%87%d8%a7/) و [این پیوست از گوگل درایو آقای سوزنچی](https://drive.google.com/drive/folders/1jWrkeOOFxsIc4iAx44ASrk4sMfkzEhlB) شما رو در مورد ساخت فونت کمک میکنه
